server {
    server_name sayonashipping.me www.sayonashipping.me;

    root /home/ubuntu/sayona-shipping-service/frontend/out;
    
    # Try static files, then fallback to html extension
    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    # Route API traffic to the backend server
    location /api/ {
        proxy_pass http://127.0.0.1:3000/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/sayonashipping.me/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/sayonashipping.me/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = www.sayonashipping.me) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = sayonashipping.me) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name sayonashipping.me www.sayonashipping.me;
    return 404; # managed by Certbot
}
