server {
    listen 80;
    server_name sayonashipping.me www.sayonashipping.me;

    root /home/ubuntu/sayona-shipping-service/frontend/out;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
