// ─────────────────────────────────────────────
// Model Schemas — Shared enums, constants, field definitions
// ─────────────────────────────────────────────

/**
 * Shipment status lifecycle
 */
const SHIPMENT_STATUS = Object.freeze({
    CREATED: 'CREATED',
    PICKED_UP: 'PICKED_UP',
    IN_TRANSIT: 'IN_TRANSIT',
    ARRIVED_AT_WAREHOUSE: 'ARRIVED_AT_WAREHOUSE',
    OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
    DELIVERED: 'DELIVERED',
    FAILED_DELIVERY: 'FAILED_DELIVERY',
    RETURNED: 'RETURNED'
});

const SHIPMENT_STATUS_VALUES = Object.values(SHIPMENT_STATUS);

/**
 * Valid shipment status transitions
 */
const SHIPMENT_STATUS_TRANSITIONS = Object.freeze({
    [SHIPMENT_STATUS.CREATED]: [SHIPMENT_STATUS.PICKED_UP, SHIPMENT_STATUS.RETURNED],
    [SHIPMENT_STATUS.PICKED_UP]: [SHIPMENT_STATUS.IN_TRANSIT, SHIPMENT_STATUS.RETURNED],
    [SHIPMENT_STATUS.IN_TRANSIT]: [SHIPMENT_STATUS.ARRIVED_AT_WAREHOUSE, SHIPMENT_STATUS.OUT_FOR_DELIVERY, SHIPMENT_STATUS.FAILED_DELIVERY],
    [SHIPMENT_STATUS.ARRIVED_AT_WAREHOUSE]: [SHIPMENT_STATUS.IN_TRANSIT, SHIPMENT_STATUS.OUT_FOR_DELIVERY],
    [SHIPMENT_STATUS.OUT_FOR_DELIVERY]: [SHIPMENT_STATUS.DELIVERED, SHIPMENT_STATUS.FAILED_DELIVERY],
    [SHIPMENT_STATUS.DELIVERED]: [],
    [SHIPMENT_STATUS.FAILED_DELIVERY]: [SHIPMENT_STATUS.OUT_FOR_DELIVERY, SHIPMENT_STATUS.RETURNED],
    [SHIPMENT_STATUS.RETURNED]: []
});

/**
 * User roles hierarchy
 */
const USER_ROLES = Object.freeze({
    ADMIN: 'admin',
    STAFF: 'staff',
    WAREHOUSE_STAFF: 'warehouse_staff',
    DELIVERY_AGENT: 'delivery_agent',
    CLIENT: 'client',
});

const USER_ROLE_VALUES = Object.values(USER_ROLES);

/**
 * Role hierarchy for authorization — higher index = more privilege
 */
const ROLE_HIERARCHY = Object.freeze({
    [USER_ROLES.CLIENT]: 0,
    [USER_ROLES.DELIVERY_AGENT]: 1,
    [USER_ROLES.WAREHOUSE_STAFF]: 2,
    [USER_ROLES.STAFF]: 3,
    [USER_ROLES.ADMIN]: 4,
});

/**
 * Quote statuses
 */
const QUOTE_STATUS = Object.freeze({
    PENDING: 'pending',
    REVIEWED: 'reviewed',
    QUOTED: 'quoted',
    ACCEPTED: 'accepted',
    REJECTED: 'rejected',
});

const QUOTE_STATUS_VALUES = Object.values(QUOTE_STATUS);

/**
 * Audit log action types
 */
const AUDIT_ACTIONS = Object.freeze({
    USER_LOGIN: 'USER_LOGIN',
    USER_REGISTER: 'USER_REGISTER',
    USER_LOGOUT: 'USER_LOGOUT',
    USER_UPDATED: 'USER_UPDATED',
    USER_LOCKED: 'USER_LOCKED',
    USER_UNLOCKED: 'USER_UNLOCKED',
    PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
    PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',
    SHIPMENT_CREATED: 'SHIPMENT_CREATED',
    SHIPMENT_UPDATED: 'SHIPMENT_UPDATED',
    SHIPMENT_DELETED: 'SHIPMENT_DELETED',
    TRACKING_EVENT_ADDED: 'TRACKING_EVENT_ADDED',
    QUOTE_SUBMITTED: 'QUOTE_SUBMITTED',
    QUOTE_STATUS_UPDATED: 'QUOTE_STATUS_UPDATED',
    CONTACT_SUBMITTED: 'CONTACT_SUBMITTED',
    CONTACT_READ: 'CONTACT_READ',
});

module.exports = {
    SHIPMENT_STATUS,
    SHIPMENT_STATUS_VALUES,
    SHIPMENT_STATUS_TRANSITIONS,
    USER_ROLES,
    USER_ROLE_VALUES,
    ROLE_HIERARCHY,
    QUOTE_STATUS,
    QUOTE_STATUS_VALUES,
    AUDIT_ACTIONS,
};
