global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'sayona-microservices'
    metrics_path: '/api/v1/metrics'
    static_configs:
      - targets:
        - 'api-auth:3000'
        - 'api-shipment:3000'
        - 'api-tracking:3000'
        - 'api:3000'
