// ─── Top Shipping Corridor Countries ───
export const COUNTRIES = [
  { value: "India", label: "India" },
  { value: "USA", label: "United States" },
  { value: "UK", label: "United Kingdom" },
  { value: "Germany", label: "Germany" },
  { value: "UAE", label: "United Arab Emirates" },
  { value: "China", label: "China" },
  { value: "Japan", label: "Japan" },
  { value: "South Korea", label: "South Korea" },
  { value: "Singapore", label: "Singapore" },
  { value: "Malaysia", label: "Malaysia" },
  { value: "Australia", label: "Australia" },
  { value: "Canada", label: "Canada" },
  { value: "France", label: "France" },
  { value: "Italy", label: "Italy" },
  { value: "Netherlands", label: "Netherlands" },
  { value: "Belgium", label: "Belgium" },
  { value: "Spain", label: "Spain" },
  { value: "Turkey", label: "Turkey" },
  { value: "Saudi Arabia", label: "Saudi Arabia" },
  { value: "Qatar", label: "Qatar" },
  { value: "Oman", label: "Oman" },
  { value: "Bangladesh", label: "Bangladesh" },
  { value: "Sri Lanka", label: "Sri Lanka" },
  { value: "Vietnam", label: "Vietnam" },
  { value: "Thailand", label: "Thailand" },
  { value: "Indonesia", label: "Indonesia" },
  { value: "Brazil", label: "Brazil" },
  { value: "Mexico", label: "Mexico" },
  { value: "South Africa", label: "South Africa" },
  { value: "Kenya", label: "Kenya" },
  { value: "Egypt", label: "Egypt" },
  { value: "Other", label: "Other" },
] as const;

export const SHIPPING_MODES = [
  { value: "FCL", label: "Full Container Load (FCL)" },
  { value: "LCL", label: "Less than Container Load (LCL)" },
  { value: "Air", label: "Air Freight" },
  { value: "Express", label: "Express / Courier" },
  { value: "Not Sure", label: "Not Sure — Advise Me" },
] as const;
